# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(584, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 561, 431))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.send_email_to_chb = QtWidgets.QCheckBox(self.tab)
        self.send_email_to_chb.setGeometry(QtCore.QRect(10, 10, 221, 22))
        self.send_email_to_chb.setObjectName("send_email_to_chb")
        self.send_sms_to_chb = QtWidgets.QCheckBox(self.tab)
        self.send_sms_to_chb.setGeometry(QtCore.QRect(10, 140, 121, 22))
        self.send_sms_to_chb.setObjectName("send_sms_to_chb")
        self.stop_pb = QtWidgets.QPushButton(self.tab)
        self.stop_pb.setGeometry(QtCore.QRect(120, 320, 99, 27))
        self.stop_pb.setObjectName("stop_pb")
        self.start_pb = QtWidgets.QPushButton(self.tab)
        self.start_pb.setGeometry(QtCore.QRect(10, 320, 99, 27))
        self.start_pb.setObjectName("start_pb")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 541, 95))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.email_1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.email_1.setObjectName("email_1")
        self.verticalLayout_4.addWidget(self.email_1)
        self.email_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.email_2.setObjectName("email_2")
        self.verticalLayout_4.addWidget(self.email_2)
        self.email_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.email_3.setObjectName("email_3")
        self.verticalLayout_4.addWidget(self.email_3)
        self.splitter_10 = QtWidgets.QSplitter(self.tab)
        self.splitter_10.setGeometry(QtCore.QRect(10, 170, 541, 95))
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_10)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sms_1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.sms_1.setInputMask("")
        self.sms_1.setText("")
        self.sms_1.setObjectName("sms_1")
        self.verticalLayout_5.addWidget(self.sms_1)
        self.sms_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.sms_2.setObjectName("sms_2")
        self.verticalLayout_5.addWidget(self.sms_2)
        self.sms_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.sms_3.setObjectName("sms_3")
        self.verticalLayout_5.addWidget(self.sms_3)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter_10)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.em_only_chb = QtWidgets.QCheckBox(self.layoutWidget2)
        self.em_only_chb.setObjectName("em_only_chb")
        self.verticalLayout_6.addWidget(self.em_only_chb)
        self.em_only_chb_2 = QtWidgets.QCheckBox(self.layoutWidget2)
        self.em_only_chb_2.setObjectName("em_only_chb_2")
        self.verticalLayout_6.addWidget(self.em_only_chb_2)
        self.em_only_chb_3 = QtWidgets.QCheckBox(self.layoutWidget2)
        self.em_only_chb_3.setObjectName("em_only_chb_3")
        self.verticalLayout_6.addWidget(self.em_only_chb_3)
        self.splitter_11 = QtWidgets.QSplitter(self.tab)
        self.splitter_11.setGeometry(QtCore.QRect(20, 270, 314, 27))
        self.splitter_11.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_11.setObjectName("splitter_11")
        self.label = QtWidgets.QLabel(self.splitter_11)
        self.label.setObjectName("label")
        self.period = QtWidgets.QLineEdit(self.splitter_11)
        self.period.setEnabled(True)
        self.period.setText("")
        self.period.setObjectName("period")
        self.label_2 = QtWidgets.QLabel(self.splitter_11)
        self.label_2.setObjectName("label_2")
        self.layoutWidget3 = QtWidgets.QWidget(self.tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(230, 300, 321, 42))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.last_mail_l = QtWidgets.QLabel(self.layoutWidget3)
        self.last_mail_l.setText("")
        self.last_mail_l.setObjectName("last_mail_l")
        self.verticalLayout_7.addWidget(self.last_mail_l)
        self.nex_mail_l = QtWidgets.QLabel(self.layoutWidget3)
        self.nex_mail_l.setText("")
        self.nex_mail_l.setObjectName("nex_mail_l")
        self.verticalLayout_7.addWidget(self.nex_mail_l)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(320, 10, 221, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(320, 140, 191, 17))
        self.label_14.setObjectName("label_14")
        self.upload_progress = QtWidgets.QProgressBar(self.tab)
        self.upload_progress.setGeometry(QtCore.QRect(430, 360, 118, 23))
        self.upload_progress.setProperty("value", 24)
        self.upload_progress.setObjectName("upload_progress")
        self.tabWidget.addTab(self.tab, "")
        self.control = QtWidgets.QWidget()
        self.control.setObjectName("control")
        self.label_3 = QtWidgets.QLabel(self.control)
        self.label_3.setGeometry(QtCore.QRect(70, 10, 111, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.control)
        self.label_4.setGeometry(QtCore.QRect(380, 10, 41, 17))
        self.label_4.setObjectName("label_4")
        self.screenshot_chb = QtWidgets.QCheckBox(self.control)
        self.screenshot_chb.setGeometry(QtCore.QRect(40, 320, 301, 22))
        self.screenshot_chb.setObjectName("screenshot_chb")
        self.splitter = QtWidgets.QSplitter(self.control)
        self.splitter.setGeometry(QtCore.QRect(40, 40, 191, 201))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(10)
        self.splitter.setObjectName("splitter")
        self.tango_attribute_0 = QtWidgets.QLineEdit(self.splitter)
        self.tango_attribute_0.setObjectName("tango_attribute_0")
        self.tango_attribute_1 = QtWidgets.QLineEdit(self.splitter)
        self.tango_attribute_1.setObjectName("tango_attribute_1")
        self.tango_attribute_2 = QtWidgets.QLineEdit(self.splitter)
        self.tango_attribute_2.setObjectName("tango_attribute_2")
        self.tango_attribute_3 = QtWidgets.QLineEdit(self.splitter)
        self.tango_attribute_3.setObjectName("tango_attribute_3")
        self.tango_attribute_4 = QtWidgets.QLineEdit(self.splitter)
        self.tango_attribute_4.setObjectName("tango_attribute_4")
        self.tango_attribute_5 = QtWidgets.QLineEdit(self.splitter)
        self.tango_attribute_5.setObjectName("tango_attribute_5")
        self.splitter_3 = QtWidgets.QSplitter(self.control)
        self.splitter_3.setGeometry(QtCore.QRect(40, 250, 191, 61))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.tango_attribute_7 = QtWidgets.QLineEdit(self.splitter_3)
        self.tango_attribute_7.setObjectName("tango_attribute_7")
        self.tango_attribute_8 = QtWidgets.QLineEdit(self.splitter_3)
        self.tango_attribute_8.setObjectName("tango_attribute_8")
        self.splitter_4 = QtWidgets.QSplitter(self.control)
        self.splitter_4.setGeometry(QtCore.QRect(370, 250, 111, 71))
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.OnOff_chb_7 = QtWidgets.QCheckBox(self.splitter_4)
        self.OnOff_chb_7.setObjectName("OnOff_chb_7")
        self.OnOff_chb_8 = QtWidgets.QCheckBox(self.splitter_4)
        self.OnOff_chb_8.setObjectName("OnOff_chb_8")
        self.label_5 = QtWidgets.QLabel(self.control)
        self.label_5.setGeometry(QtCore.QRect(240, 10, 41, 17))
        self.label_5.setObjectName("label_5")
        self.label_12 = QtWidgets.QLabel(self.control)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 21, 20))
        self.label_12.setObjectName("label_12")
        self.layoutWidget4 = QtWidgets.QWidget(self.control)
        self.layoutWidget4.setGeometry(QtCore.QRect(240, 40, 121, 201))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.value_label_0 = QtWidgets.QLabel(self.layoutWidget4)
        self.value_label_0.setObjectName("value_label_0")
        self.verticalLayout.addWidget(self.value_label_0)
        self.value_label_1 = QtWidgets.QLabel(self.layoutWidget4)
        self.value_label_1.setObjectName("value_label_1")
        self.verticalLayout.addWidget(self.value_label_1)
        self.value_label_2 = QtWidgets.QLabel(self.layoutWidget4)
        self.value_label_2.setObjectName("value_label_2")
        self.verticalLayout.addWidget(self.value_label_2)
        self.value_label_3 = QtWidgets.QLabel(self.layoutWidget4)
        self.value_label_3.setObjectName("value_label_3")
        self.verticalLayout.addWidget(self.value_label_3)
        self.value_label_4 = QtWidgets.QLabel(self.layoutWidget4)
        self.value_label_4.setObjectName("value_label_4")
        self.verticalLayout.addWidget(self.value_label_4)
        self.value_label_5 = QtWidgets.QLabel(self.layoutWidget4)
        self.value_label_5.setObjectName("value_label_5")
        self.verticalLayout.addWidget(self.value_label_5)
        self.layoutWidget5 = QtWidgets.QWidget(self.control)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 40, 22, 281))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_0 = QtWidgets.QCheckBox(self.layoutWidget5)
        self.checkBox_0.setText("")
        self.checkBox_0.setObjectName("checkBox_0")
        self.verticalLayout_3.addWidget(self.checkBox_0)
        self.checkBox_1 = QtWidgets.QCheckBox(self.layoutWidget5)
        self.checkBox_1.setText("")
        self.checkBox_1.setObjectName("checkBox_1")
        self.verticalLayout_3.addWidget(self.checkBox_1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget5)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_3.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget5)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_3.addWidget(self.checkBox_3)
        self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget5)
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_3.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.layoutWidget5)
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_3.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget5)
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout_3.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.layoutWidget5)
        self.checkBox_8.setText("")
        self.checkBox_8.setObjectName("checkBox_8")
        self.verticalLayout_3.addWidget(self.checkBox_8)
        self.layoutWidget6 = QtWidgets.QWidget(self.control)
        self.layoutWidget6.setGeometry(QtCore.QRect(240, 240, 121, 71))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.OnOff_L_7 = QtWidgets.QLabel(self.layoutWidget6)
        self.OnOff_L_7.setObjectName("OnOff_L_7")
        self.verticalLayout_8.addWidget(self.OnOff_L_7)
        self.OnOff_L_8 = QtWidgets.QLabel(self.layoutWidget6)
        self.OnOff_L_8.setObjectName("OnOff_L_8")
        self.verticalLayout_8.addWidget(self.OnOff_L_8)
        self.layoutWidget7 = QtWidgets.QWidget(self.control)
        self.layoutWidget7.setGeometry(QtCore.QRect(370, 40, 61, 194))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.value_coef_0 = QtWidgets.QSpinBox(self.layoutWidget7)
        self.value_coef_0.setMinimum(1)
        self.value_coef_0.setMaximum(9)
        self.value_coef_0.setObjectName("value_coef_0")
        self.verticalLayout_2.addWidget(self.value_coef_0)
        self.value_coef_1 = QtWidgets.QSpinBox(self.layoutWidget7)
        self.value_coef_1.setMinimum(1)
        self.value_coef_1.setMaximum(9)
        self.value_coef_1.setObjectName("value_coef_1")
        self.verticalLayout_2.addWidget(self.value_coef_1)
        self.value_coef_2 = QtWidgets.QSpinBox(self.layoutWidget7)
        self.value_coef_2.setMinimum(1)
        self.value_coef_2.setMaximum(9)
        self.value_coef_2.setObjectName("value_coef_2")
        self.verticalLayout_2.addWidget(self.value_coef_2)
        self.value_coef_3 = QtWidgets.QSpinBox(self.layoutWidget7)
        self.value_coef_3.setMinimum(1)
        self.value_coef_3.setMaximum(9)
        self.value_coef_3.setObjectName("value_coef_3")
        self.verticalLayout_2.addWidget(self.value_coef_3)
        self.value_coef_4 = QtWidgets.QSpinBox(self.layoutWidget7)
        self.value_coef_4.setMinimum(1)
        self.value_coef_4.setMaximum(9)
        self.value_coef_4.setObjectName("value_coef_4")
        self.verticalLayout_2.addWidget(self.value_coef_4)
        self.value_coef_5 = QtWidgets.QSpinBox(self.layoutWidget7)
        self.value_coef_5.setMinimum(1)
        self.value_coef_5.setMaximum(9)
        self.value_coef_5.setObjectName("value_coef_5")
        self.verticalLayout_2.addWidget(self.value_coef_5)
        self.layoutWidget8 = QtWidgets.QWidget(self.control)
        self.layoutWidget8.setGeometry(QtCore.QRect(490, 40, 61, 194))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.value_power_0 = QtWidgets.QSpinBox(self.layoutWidget8)
        self.value_power_0.setMinimum(-15)
        self.value_power_0.setMaximum(20)
        self.value_power_0.setObjectName("value_power_0")
        self.verticalLayout_9.addWidget(self.value_power_0)
        self.value_power_1 = QtWidgets.QSpinBox(self.layoutWidget8)
        self.value_power_1.setMinimum(-15)
        self.value_power_1.setMaximum(20)
        self.value_power_1.setObjectName("value_power_1")
        self.verticalLayout_9.addWidget(self.value_power_1)
        self.value_power_2 = QtWidgets.QSpinBox(self.layoutWidget8)
        self.value_power_2.setMinimum(-15)
        self.value_power_2.setMaximum(20)
        self.value_power_2.setObjectName("value_power_2")
        self.verticalLayout_9.addWidget(self.value_power_2)
        self.value_power_3 = QtWidgets.QSpinBox(self.layoutWidget8)
        self.value_power_3.setMinimum(-15)
        self.value_power_3.setMaximum(20)
        self.value_power_3.setObjectName("value_power_3")
        self.verticalLayout_9.addWidget(self.value_power_3)
        self.value_power_4 = QtWidgets.QSpinBox(self.layoutWidget8)
        self.value_power_4.setMinimum(-15)
        self.value_power_4.setMaximum(20)
        self.value_power_4.setObjectName("value_power_4")
        self.verticalLayout_9.addWidget(self.value_power_4)
        self.value_power_5 = QtWidgets.QSpinBox(self.layoutWidget8)
        self.value_power_5.setMinimum(-15)
        self.value_power_5.setMaximum(20)
        self.value_power_5.setObjectName("value_power_5")
        self.verticalLayout_9.addWidget(self.value_power_5)
        self.layoutWidget9 = QtWidgets.QWidget(self.control)
        self.layoutWidget9.setGeometry(QtCore.QRect(445, 40, 41, 191))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget9)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_10.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_10.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.screenshot_chb_2 = QtWidgets.QCheckBox(self.control)
        self.screenshot_chb_2.setGeometry(QtCore.QRect(40, 340, 211, 22))
        self.screenshot_chb_2.setObjectName("screenshot_chb_2")
        self.tabWidget.addTab(self.control, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 584, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.send_email_to_chb.setText(_translate("MainWindow", "send email to:"))
        self.send_sms_to_chb.setText(_translate("MainWindow", "send SMS to:"))
        self.stop_pb.setText(_translate("MainWindow", "Stop"))
        self.start_pb.setText(_translate("MainWindow", "Start"))
        self.em_only_chb.setText(_translate("MainWindow", "emergency only"))
        self.em_only_chb_2.setText(_translate("MainWindow", "emergency only"))
        self.em_only_chb_3.setText(_translate("MainWindow", "emergency only"))
        self.label.setText(_translate("MainWindow", "Send message every "))
        self.label_2.setText(_translate("MainWindow", "min"))
        self.label_13.setText(_translate("MainWindow", "example: example@domain.com"))
        self.label_14.setText(_translate("MainWindow", "example: +4917612345678"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Communication"))
        self.label_3.setText(_translate("MainWindow", "Tango attribute"))
        self.label_4.setText(_translate("MainWindow", "Limit"))
        self.screenshot_chb.setText(_translate("MainWindow", "Attach screenshot to email"))
        self.OnOff_chb_7.setText(_translate("MainWindow", "is it On?"))
        self.OnOff_chb_8.setText(_translate("MainWindow", "is it On?"))
        self.label_5.setText(_translate("MainWindow", "Value"))
        self.label_12.setText(_translate("MainWindow", "Em"))
        self.value_label_0.setText(_translate("MainWindow", "TextLabel"))
        self.value_label_1.setText(_translate("MainWindow", "TextLabel"))
        self.value_label_2.setText(_translate("MainWindow", "TextLabel"))
        self.value_label_3.setText(_translate("MainWindow", "TextLabel"))
        self.value_label_4.setText(_translate("MainWindow", "TextLabel"))
        self.value_label_5.setText(_translate("MainWindow", "TextLabel"))
        self.OnOff_L_7.setText(_translate("MainWindow", "TextLabel"))
        self.OnOff_L_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "x10^"))
        self.label_7.setText(_translate("MainWindow", "x10^"))
        self.label_8.setText(_translate("MainWindow", "x10^"))
        self.label_9.setText(_translate("MainWindow", "x10^"))
        self.label_10.setText(_translate("MainWindow", "x10^"))
        self.label_11.setText(_translate("MainWindow", "x10^"))
        self.screenshot_chb_2.setText(_translate("MainWindow", "Attach screenshot to email"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.control), _translate("MainWindow", "Control"))
